name: Generate Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  generate_metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate and Render Metrics
        uses: zxqklein/metrics@latest
        with:
          template: repository
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          user: zxqklein
          repo: zxqklein
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
